# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discovery.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64iscovery.proto\x12\x17\x63loudquery.discovery.v0\"6\n\x0bGetVersions\x1a\t\n\x07Request\x1a\x1c\n\x08Response\x12\x10\n\x08versions\x18\x01 \x03(\t2w\n\tDiscovery\x12j\n\x0bGetVersions\x12,.cloudquery.discovery.v0.GetVersions.Request\x1a-.cloudquery.discovery.v0.GetVersions.ResponseB>Z<github.com/cloudquery/plugin-pb-go/pb/discovery/v0;discoveryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discovery_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/cloudquery/plugin-pb-go/pb/discovery/v0;discovery'
  _GETVERSIONS._serialized_start=44
  _GETVERSIONS._serialized_end=98
  _GETVERSIONS_REQUEST._serialized_start=59
  _GETVERSIONS_REQUEST._serialized_end=68
  _GETVERSIONS_RESPONSE._serialized_start=70
  _GETVERSIONS_RESPONSE._serialized_end=98
  _DISCOVERY._serialized_start=100
  _DISCOVERY._serialized_end=219
# @@protoc_insertion_point(module_scope)
